blacklist = [
	"scratch",
]

sort_order = [
	"tmux",
	"config",
	"tmuxinator",
	"zoxide",
]

[[session]]
name = "üè† Home"
# startup_command = "tmux split-window -h \\; select-pane -L \\; send-keys 'yazi' C-m"
startup_command = "tmux rename-window 'Yazi' && yazi"

[[session]]
name = "‚úàÔ∏è Blueweb"
path = "~/Developer/bw-blueweb"
startup_command = "tmux rename-window 'Vim' && vim"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["Tests"]

[[session]]
name = "üñ•Ô∏è BW-Servers"
path = "~/Developer/bw-blueweb"
startup_command = "tmux rename-window 'MitmProxy' && apirequests"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["Application" , "Graphql"]

[[session]]
name = "‚öôÔ∏è Dotfiles"
path = "~/dotfiles"
startup_command = "tmux rename-window 'Vim' && vim"
preview_command = "eza --all --git --icons --color=always {}"

[[window]]
name = "Tests"
startup_script = "clear"

[[window]]
name = "Opencode"
startup_script = "opencode"

[[window]]
name = "Application"
startup_script = "appstart"

[[window]]
name = "Graphql"
startup_script = "gqlstart"
