blacklist = [
	"scratch",
	"opencode"
]

sort_order = [
	"tmux",
	"config",
	"zoxide",
]

[[session]]
name = "ğŸ  Home"
# startup_command = "tmux split-window -h \\; select-pane -L \\; send-keys 'yazi' C-m"
startup_command = "tmux rename-window 'Yazi' && yazi"

[[session]]
name = "ğŸ›« Blueweb"
path = "~/Developer/bw-blueweb"
startup_command = "tmux rename-window 'Vim' && vim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "ğŸ§ª Blueweb Specs"
path = "~/Developer/bw-blueweb"
startup_command = "tmux rename-window 'Tests' && clear"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "ğŸ–¥ï¸ BW-Servers"
path = "~/Developer/bw-blueweb"
startup_command = "tmux rename-window 'MitmProxy' && apirequests"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["Application" , "Graphql"]

[[session]]
name = "ğŸ‘· Dotfiles"
path = "~/dotfiles"
startup_command = "tmux rename-window 'Vim' && vim"
preview_command = "eza --all --git --icons --color=always {}"

[[window]]
name = "Application"
startup_script = "appstart"

[[window]]
name = "Graphql"
startup_script = "gqlstart"
