blacklist = [
	"scratch"
]

sort_order = [
	"tmux",
	"tmuxinator",
	"config",
	"zoxide",
]

[[session]]
name = "ğŸ  Home"
startup_command = "tmux split-window -h \\; select-pane -L \\; send-keys 'yazi' C-m"
